### ISSUE TITLE
Add support for TTS

### ISSUE THREAD

**Issue by utack** [relan/omim#1]
Maybe support for the Android System TTS Engine could be added.
Devices without Google TTS still have Pico TTS available.

**Comment by relan** [comment]
Version 5.2 added voice suggestions. Is this what you are requesting?

**Comment by utack** [comment]
I was hoping to use PicoTTS for spoken navigation instructions.

**Comment by twzkxkan** [comment]
@utack 5.2 code hasn't been merged yet, so the spoken navigation features aren't present in this fork.

**Comment by utack** [comment]
Thanks for the clarification @twzkxkan 
The [guide over at maps.me](http://maps.me/files/MAPS.ME%20User%20Guide%20v5.1.pdf) seems to be ahead of time then, I thought this was Google Play version specific.

**Comment by relan** [comment]
This project is [dead](https://github.com/relan/omim/blob/master/README.md).
