### ISSUE TITLE
Help needed: server infrastructure for the project

### ISSUE THREAD

**Issue by relan** [relan/omim#2]
In order to be truly community-driven project, we need to run own servers with mapping data. The servers of the upstream project are a property of Mail.ru Group with restrictive ToS.

What is required for now:

* Figure out what the server infrastructure should look like.
* Figure out how to build the required data.
* Automate builds of the data.
* Find a hosting that can potentially serve petabytes (?) of traffic per month.
* Maintain all this.

**Comment by pizzamaker** [comment]
We can surely ask MAPS.ME how they handle their own servers, no?

**Comment by relan** [comment]
> We can surely ask MAPS.ME how they handle their own servers, no?

They have documentation:
* https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#map-servers
* https://github.com/mapsme/omim/blob/master/docs/MAPS.md

**Comment by twzkxkan** [comment]
Would MAPS.ME be ok with us mirroring their packaged [maps](http://direct.mapswithme.com/direct/)? We could possibly distributed them via bittorrent even.

**Comment by relan** [comment]
> Would MAPS.ME be ok with us mirroring their packaged maps?

I think they won't object but they can stop publishing updates at any time, like they did with [APKs](http://maps.me/apk/).

BTW latest data files occupy 28 GB.

> We could possibly distribute them via bittorrent even.

Do you mean adding bittorrent protocol support into the Android app? Some kind of p2p communication can help to distribute big files. It's an interesting idea.

**Comment by twzkxkan** [comment]
I don't believe they stopped updating that APK page, they choose to publish infrequently. But you're right that we shouldn't depend on it.

>Do you mean adding bittorrent protocol support into the Android app?
I did not think of that, but it may be an option. Personally, I'd prefer to seed from a desktop or cloud instance.

**Comment by wkfobixp** [comment]
If you're going to run your own server you should be aware of a [vulnerability](https://github.com/mapsme/omim/issues/1073) in how MAPS.ME communicates with their app. I'm not sure if this fork implements the feature the same way, but there may be more potential risks for users in the code.

**Comment by relan** [comment]
> I'm not sure if this fork implements the feature the same way

The networking code remained untouched.

> there may be more potential risks for users in the code.

Agree. It's another reason to make an Internet-less version (see #3).

**Comment by kaiyou** [comment]
Regarding:

>Find a hosting that can potentially serve petabytes (?) of traffic per month.

I do not believe that petabytes are to be expected from F-droid users.

Would it be reasonable to distribute the load among voluntarily setup Web servers (and maybe simply distribute a self-updating Docker image, then maintain a mirror list or rr DNS)? Does the download part rely on TLS?

**Comment by relan** [comment]
> I do not believe that petabytes are to be expected from F-droid users.

I don't believe either. Tens of gigabytes sound more plausible.

> Would it be reasonable to distribute the load among voluntarily setup Web servers just like most FOSS software distros operate (and maybe simply distribute a self-updating Docker image, then maintain a mirror list or rr DNS)?

I have no experience in content delivery, I have no idea how to do it. That's why I created this ticket. :)

> Does the download part rely on TLS?

The upstream has recently added TLS support to the client part.

**Comment by Thrilleratplay** [comment]
Does any know the licence for the MWM format?  Mirroring the official Maps.me files may be fine but providing different versions outside of their control may be frowned upon.  I would rather stay on good term with the Maps.me team.

As this is Openstreetmap data, I was wondering if they could provide a mirror and, if permitted, update the files. Or ask universities to mirror the files.

The P2P route sounds like the way to go.  Can BitTorrent handle updates to files?  That sounds more like BitTorrent Sync (not FOSS).  Taking a look at [alternative-internet](https://github.com/redecentralize/alternative-internet), there are a few Sync like projects but I am not sure if any are compatible with Android.

**Comment by relan** [comment]
> The P2P route sounds like the way to go. Can BitTorrent handle updates to files?

BitTorrent protocol itself does not have such functionality, but it can be [combined with RSS](https://en.wikipedia.org/wiki/Broadcatching#RSS.2BBitTorrent).

**Comment by LuccoJ** [comment]
There aren't any exceptionally convincing BitTorrent clients for Android, either... there is the old, semi-open FrostWire, and there is the command-line aria2 which is not packaged in F-Droid yet although it has a simple Android app "wrapper". Syncthing could be considered also (which IS available in F-Droid), although its intended purpose is different.

**Comment by Thrilleratplay** [comment]
@LuccoJ I am sure the intent would not to use a third party BitTorrent application but instead update maps using an embedded code to use the BitTorrent protocol.  That is how [Blizzard's Downloader](http://us.blizzard.com/en-us/company/about/legal-faq.html) works under the hood.

**Comment by kaiyou** [comment]
Goig the P2P way for end-user downloads looks nice on paper, but I do not believe it is appropriate: most mobile users will download maps from mobile ISPs or WiFi networks they do not manage, thus making bittorrent and other p2p protocols difficult to use.

Bittorrent could be interesting to maintain a pool of mirrors synced, especially if, as @Thrilleratplay stated, we intend to use a copy of the official Maps.me data. Bittorrent would then allow replication at a very moderate cost for official map servers (one download server that would seed data for the mirrors).

It sounds like a complex way to go however. Maybe people from Maps.me have already implemented a synchronization solution and would be kind enough to discuss the principles with the community?

**Comment by ighsiwwx** [comment]
I don't think P2P on mobile devices is a good idea. It's much better to host content on devices without limited batteries and with unmetered internet connections.

**Comment by relan** [comment]
I'm thinking about the following network structure.

1. Main server: stores and distributes .torrent files via HTTPS protocol. Each .torrent describes mapping data for a single region. This will require very little traffic and storage.

2. Seeders: PCs, home servers, seedboxes that distribute data using BitTorrent protocol. Anyone can join by just downloading .torrent files from the main server and adding them to their BitTorrent client.

3. Leechers: Android devices that use HTTPS protocol to download .torrent files from the main server and BitTorrent protocol to download data from multiple seeders. They do not upload data.

**Comment by relan** [comment]
Nobody offered any help with server infrastructure after all. This and some other [considerations](https://github.com/relan/omim/blob/master/README.md) made me shut this project down.
