### ISSUE TITLE
Release a version without Internet access

### ISSUE THREAD

**Issue by ghost** [relan/omim#3]
Firstly, thank you for your efforts. Maintaining software is not an easy job, and I understand if you found recent events frustrating.

That aside, this app works perfectly well without Internet access. Releasing a gimped version like this is not ideal, but users can still copy over their own maps. I can help with a new name and replacement for the copyrighted logos if needed.

I'm optimistic that we'll figure out a map hosting solution, and until then this might be the best option.

**Comment by relan** [comment]
> That aside, this app works perfectly well without Internet access. Releasing a gimped version like this is not ideal, but users can still copy over their own maps.

That's true, but if user will try to download a map, the app will crash. This is a terribly bad UX.

> I can help with a new name and replacement for the copyrighted logos if needed.

Any help is welcome! Rebranding is the next big task if we manage to find people who will do the server-side work.

**Comment by twzkxkan** [comment]
Pardon my ignorance, but would it be possible to comment out the code for the download menu (and other relevant code if necessary)? We could get a usable app back in F-Droid in a few days if branding is our only roadblock. 

Rebranding is a prerequisite for adding a new server anyway.

**Comment by relan** [comment]
> would it be possible to comment out the code for the download menu (and other relevant code as necessary)?

Sure. But it's not enough because it will still confuse users. There should be UI explaining where to get the maps, where to put them on the device, etc.

> We could get a usable app back in F-Droid in a few days if branding is our only roadblock. 

I don't think we need to rush into F-Droid repo. I'd prefer to put the app back only after I'm sure that the fork will survive in the long run.

> Rebranding is a prerequisite for adding a new server anyway.

You are right. But rebranding is definitely a doable thing. I'm not so sure about hosting.

**Comment by relan** [comment]
This project is [dead](https://github.com/relan/omim/blob/master/README.md).
