### ISSUE TITLE
Open OSM links

### ISSUE THREAD

**Issue by moshpirit** [relan/omim#4]
Would be possible to open OSM links such
http://osm.org/go/(code1)--?m=&way=(code2) ? This way when someone share with us a location we could just open it with MAPS.ME

**Comment by ighsiwwx** [comment]
Consider raising the issue [upstream](https://github.com/mapsme/omim/issues).

**Comment by moshpirit** [comment]
Not a native English speaker, what do you mean? That it's already been implemented or that I should do it and make a pull request? (Because I have no idea of coding)

**Comment by ighsiwwx** [comment]
This repo is a fork of the main codebase, so most changes take place in the official repo. When the changes are made there, this repo can pick them up.

**Comment by moshpirit** [comment]
Oh, OK then I'll do the request there, thanks! :)

**Comment by moshpirit** [comment]
BTW, I found the repo by F-Droid, should I open an issue on the F-droid repo in order to change it?

**Comment by relan** [comment]
> I found the repo by F-Droid, should I open an issue on the F-droid repo in order to change it?

No. F-Droid merely builds and distributes apps. They have nothing to do with the fuctionality of particular apps.

**Comment by moshpirit** [comment]
No, I mean that the associated website for issues is this fork, not the original repo.

**Comment by relan** [comment]
> I mean that the associated website for issues is this fork, not the original repo.

F-Droid has moved this project to archive, so there is hardly any sense in changing anything in F-Droid's description of it.

**Comment by relan** [comment]
This project is [dead](https://github.com/relan/omim/blob/master/README.md).
